#ddev-generated
name: ðŸš€ Deploy via rsync

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: ðŸš€ Deploy to server
    runs-on: ubuntu-latest
    # environment: production # Uncomment and set if using GitHub Environments
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DEST: "/var/www/html/your-site/" # REPLACE WITH YOUR REMOTE PATH

    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸ” Check Secrets
        run: |
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "::error::Secret SSH_HOST is not set or empty. Please check your Repository Secrets."
            exit 1
          fi
          if [ -z "${{ secrets.SSH_USER }}" ]; then
            echo "::error::Secret SSH_USER is not set or empty. Please check your Repository Secrets."
            exit 1
          fi
          if [ -z "${{ secrets.SSH_KEY }}" ]; then
            echo "::error::Secret SSH_KEY is not set or empty. Please check your Repository Secrets."
            exit 1
          fi

      - name: ðŸªª Set SSH connection
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host remote
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: ðŸš€ Sync files
        run: |
          # Add your rsync commands here
          # Example:
          # echo "ðŸ“¦ Deploying theme..."
          # rsync -avO --exclude /.git/ -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy.key" ./wp-content/themes/my-theme/ ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEST }}/wp-content/themes/my-theme/
        env:
          SSH_HOST: remote
